storage_destination = "D:/Anul III/Phyton/A9/Storage"
db_username = "postgres"
db_pass = "1234"
db_port = "5432"
sqlite_connection_string = "sqlite:///C:/sqlite/sqlite-tools-win32-x86-3340000/storage.db"
